# Generated by Django 2.2.5 on 2019-09-11 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=50)),
                ('companyregistration', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='SicCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sicnumber', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=50)),
                ('transaction_timestamp', models.DateTimeField(auto_now_add=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.Counterparty')),
            ],
            options={
                'ordering': ['transaction_timestamp'],
            },
        ),
        migrations.AddField(
            model_name='counterparty',
            name='sicCodes',
            field=models.ManyToManyField(related_name='counterparties', to='transactions.SicCode'),
        ),
    ]
