# Generated by Django 2.2.5 on 2019-09-04 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(blank=True, max_length=50)),
                ('companyregistration', models.CharField(max_length=50)),
                ('image', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SicCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sicnumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('transaction_timestamp', models.CharField(max_length=50)),
                ('counterparty', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.Counterparty')),
            ],
        ),
        migrations.AddField(
            model_name='counterparty',
            name='sicCodes',
            field=models.ManyToManyField(blank=True, related_name='counterparties', to='transactions.SicCode'),
        ),
    ]
