# Generated by Django 2.2.5 on 2019-09-04 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['transaction_timestamp']},
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='companyname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='companyregistration',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='sicCodes',
            field=models.ManyToManyField(related_name='counterparties', to='transactions.SicCode'),
        ),
        migrations.AlterField(
            model_name='siccode',
            name='sicnumber',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='counterparty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.Counterparty'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
