# Generated by Django 2.2.5 on 2019-09-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siccode',
            name='sicnumber',
            field=models.CharField(max_length=20),
        ),
    ]
