# Generated by Django 2.2.5 on 2019-09-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20190904_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='companyregistration',
            field=models.CharField(max_length=8),
        ),
    ]
