# Generated by Django 2.2.5 on 2019-09-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20190911_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siccode',
            name='sicnumber',
            field=models.CharField(max_length=200),
        ),
    ]
