# Generated by Django 2.2.5 on 2019-09-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20190911_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='note',
            field=models.CharField(default='Spoke to Christina from accounting. Thenext payment will be late.', max_length=200),
            preserve_default=False,
        ),
    ]
