# Generated by Django 2.2.5 on 2019-09-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20190904_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siccode',
            name='sicnumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
