# Generated by Django 2.2.5 on 2019-09-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20190905_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siccode',
            name='sicnumber',
            field=models.CharField(max_length=8),
        ),
    ]
