# Generated by Django 2.2.5 on 2019-09-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20190905_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(max_length=3),
        ),
    ]
