# Generated by Django 2.2.5 on 2019-09-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20190905_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counterparty',
            name='image',
        ),
    ]
